#!/usr/bin/expect -f
# SPDX-FileCopyrightText: 2023 Iván SZKIBA
#
# SPDX-License-Identifier: AGPL-3.0-only

set width 114
set height 20

set base [file rootname [file tail $argv0]]
set send_human {.1 .3 1 .05 0.5}
set stty_init "cols $width rows $height"

spawn asciinema rec --overwrite ${base}.cast
expect "\$ "
send -h "docker run --rm -it -e K6X_BUILDER_SERVICE=\$K6X_BUILDER_SERVICE -v \$PWD:/home/k6x szkiba/k6x run script.js\r"
expect "\$ "
sleep 2
send \x04
expect eof
