# SPDX-FileCopyrightText: 2023 Iván SZKIBA
#
# SPDX-License-Identifier: AGPL-3.0-only

name: lint
on:
  pull_request:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docs/**'
      - README.md
      - 'releases/**'

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: REUSE linter
        uses: fsfe/reuse-action@v5
        with:
          args: lint
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false
      - name: Go linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.54
          args: --timeout=30m
          install-mode: binary
